# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: d:/vivado/ZCU104/InnerProbe/Src/constarins/constrain.xdc

# Block Designs: bd/InnerProbe/InnerProbe.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe || ORIG_REF_NAME==InnerProbe} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_AXI_DELAY_0_0/InnerProbe_AXI_DELAY_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_AXI_DELAY_0_0 || ORIG_REF_NAME==InnerProbe_AXI_DELAY_0_0} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_AXI_ProbeDetector_0_0/InnerProbe_AXI_ProbeDetector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_AXI_ProbeDetector_0_0 || ORIG_REF_NAME==InnerProbe_AXI_ProbeDetector_0_0} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_AXI_Signal_Delay_0_0/InnerProbe_AXI_Signal_Delay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_AXI_Signal_Delay_0_0 || ORIG_REF_NAME==InnerProbe_AXI_Signal_Delay_0_0} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_Cap_0_0/InnerProbe_Cap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_Cap_0_0 || ORIG_REF_NAME==InnerProbe_Cap_0_0} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_DST_reg_0_0/InnerProbe_DST_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_DST_reg_0_0 || ORIG_REF_NAME==InnerProbe_DST_reg_0_0} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_SRC_reg_0_0/InnerProbe_SRC_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_SRC_reg_0_0 || ORIG_REF_NAME==InnerProbe_SRC_reg_0_0} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_clk_wiz_0_0/InnerProbe_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_clk_wiz_0_0 || ORIG_REF_NAME==InnerProbe_clk_wiz_0_0} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_xbar_0/InnerProbe_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_xbar_0 || ORIG_REF_NAME==InnerProbe_xbar_0} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_ps8_0_axi_periph_0/InnerProbe_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_ps8_0_axi_periph_0 || ORIG_REF_NAME==InnerProbe_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_rst_clk_wiz_0_100M_0/InnerProbe_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==InnerProbe_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_zynq_ultra_ps_e_0_0/InnerProbe_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==InnerProbe_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_auto_ds_0/InnerProbe_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_auto_ds_0 || ORIG_REF_NAME==InnerProbe_auto_ds_0} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_auto_pc_0/InnerProbe_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_auto_pc_0 || ORIG_REF_NAME==InnerProbe_auto_pc_0} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_auto_ds_1/InnerProbe_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_auto_ds_1 || ORIG_REF_NAME==InnerProbe_auto_ds_1} -quiet] -quiet

# IP: bd/InnerProbe/ip/InnerProbe_auto_pc_1/InnerProbe_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InnerProbe_auto_pc_1 || ORIG_REF_NAME==InnerProbe_auto_pc_1} -quiet] -quiet

# XDC: bd/InnerProbe/InnerProbe_ooc.xdc
