# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_msg_config -id {Physopt 32-662} -limit 9999
set_msg_config -id {Physopt 32-668} -limit 9999
set_msg_config -id {Physopt 32-702} -limit 9999
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.cache/wt [current_project]
set_property parent.project_path d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu104:part0:1.1 [current_project]
set_property ip_repo_paths d:/vivado/ZCU104/InnerProbe/Src/IPs [current_project]
update_ip_catalog
set_property ip_output_repo d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib d:/vivado/ZCU104/InnerProbe/Src/sources/InnerProbe_top.v
add_files d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/InnerProbe.bd
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_clk_wiz_0_0/InnerProbe_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_clk_wiz_0_0/InnerProbe_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_clk_wiz_0_0/InnerProbe_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_xbar_0/InnerProbe_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_rst_clk_wiz_0_100M_0/InnerProbe_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_rst_clk_wiz_0_100M_0/InnerProbe_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_rst_clk_wiz_0_100M_0/InnerProbe_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_zynq_ultra_ps_e_0_0/InnerProbe_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_zynq_ultra_ps_e_0_0/InnerProbe_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_synthesis false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_auto_ds_0/InnerProbe_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_auto_ds_0/InnerProbe_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_auto_ds_0/InnerProbe_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_auto_pc_0/InnerProbe_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_auto_ds_1/InnerProbe_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_auto_ds_1/InnerProbe_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_auto_ds_1/InnerProbe_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/ip/InnerProbe_auto_pc_1/InnerProbe_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/ZCU104/InnerProbe/Scripts/InnerProbe/InnerProbe.srcs/sources_1/bd/InnerProbe/InnerProbe_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc d:/vivado/ZCU104/InnerProbe/Src/constarins/constrain.xdc
set_property used_in_implementation false [get_files d:/vivado/ZCU104/InnerProbe/Src/constarins/constrain.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top InnerProbe_top -part xczu7ev-ffvc1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef InnerProbe_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file InnerProbe_top_utilization_synth.rpt -pb InnerProbe_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
